from pathlib import Path
import os

# Optional Playwright smoke test. Run from any CWD with: python tests/prototypes/reading-toc-r3/verify-compact-h1.py
from playwright.sync_api import sync_playwright

repo=Path(__file__).resolve().parents[3]
page_path=repo/'docs/framework/prototypes/reading-toc-r3/compact-toc.html'
output=Path(os.environ.get('TOC_SCREENSHOT_DIR', '/tmp/opendesk-toc-r3-evidence'))
output.mkdir(parents=True, exist_ok=True)
passed=[]
def check(test,msg):
    assert test,msg
    passed.append(msg)

with sync_playwright() as p:
    browser=p.chromium.launch(headless=True, **({'executable_path':os.environ['CHROME_BIN']} if os.environ.get('CHROME_BIN') else {}))
    try:
        page=browser.new_page(viewport={'width':1380,'height':900},device_scale_factor=1,reduced_motion='reduce')
        errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
        page.set_content(page_path.read_text(), wait_until="load")
        links=page.locator('.docs-toc-link')
        check(links.count() >= 5,'文章模式有多个顶层章节')
        check(page.locator('a[data-target="article-appendix"]').count()==1,'普通文章正文中的第二 H1 必须进入目录')
        check(page.locator('a[data-target="article-end"]').count()==0,'一级视图只显示顶层节点')
        check(page.locator('.docs-toc-link',has_text='从目录开始，读懂长文').count()==0,'文章页面标题可按明确身份排除')
        page.get_by_role('button',name='完整目录').click()
        check(page.locator('a[data-target="article-end"]').count()==1,'完整目录包含 H1 后的 H2')
        page.locator('a[data-target="article-appendix"]').click()
        page.wait_for_timeout(300)
        check(page.locator('[aria-current="location"]').get_attribute('data-target')=='article-appendix','文章 H1 点击成功定位')
        check(page.evaluate('window.scrollY') > 0,'文章点击触发滚动')
        page.screenshot(path=str(output/'opendesk-toc-r3-article.png'),animations='disabled')
        page.get_by_role('button',name='对话').click()
        page.get_by_role('button',name='一级目录').click()
        check(page.locator('a[data-target="chat-answer-main"]').count()==1,'回答一的首个 H1 进入目录')
        check(page.locator('a[data-target="chat-phase-two"]').count()==1,'同一回答中间的第二 H1 进入目录')
        check(page.locator('a[data-target="chat-next-answer-h1"]').count()==1,'下一条独立 AI 回答中的 H1 进入目录')
        check(page.locator('a[data-target="chat-overview"]').count()==0,'一级视图不混入 H2')
        check(page.locator('a[data-target="chat-next-boundary"]').count()==0,'第二条回答 H2 不上浮为第一层')
        page.locator('.docs-toc-panel').screenshot(path=str(output/'opendesk-toc-r3-chat-top.png'),animations='disabled')
        page.get_by_role('button',name='完整目录').click()
        check(page.locator('a[data-target="chat-overview"]').count()==1,'H1 下的 H2 正确显示')
        check(page.locator('a[data-target="chat-next-boundary"]').count()==1,'不同回答的 H2 正确归属')
        check(page.locator('a[data-target="chat-summary-one"]').count()==1 and page.locator('a[data-target="chat-summary-two"]').count()==1,'同名标题在不同内容片段中保持独立')
        check(page.locator('a[data-target="chat-next-summary"]').count()==1,'第二条回答中的同名标题不会丢失')
        page.locator('a[data-target="chat-actions"]').click()
        page.wait_for_timeout(450)
        check(page.locator('[aria-current="location"]').get_attribute('data-target')=='chat-actions','跨内容片段定位目标准确')
        check(page.evaluate('document.querySelector(".chat-scroll").scrollTop')>0,'跳转滚动对话内容容器')
        check(page.eval_on_selector('#chat-actions','el=>el.closest("[data-part]").dataset.part')=='3','点击第三个片段的章节确实进入第三片段')
        page.get_by_role('button',name='当前章节').click()
        check(page.locator('a[data-target="chat-phase-two"]').count()==1,'当前章节视图保留所属的 H1')
        check(page.locator('a[data-target="chat-next-answer-h1"]').count()==1,'当前章节视图保留其它回答的顶层入口')
        check(page.locator('a[data-target="chat-actions"]').count()==1,'当前章节视图保留当前回答的 H2')
        page.get_by_role('button',name='完整目录').click()
        page.locator('a[data-target="chat-summary-one"]').click()
        page.wait_for_timeout(300)
        check(page.locator('[aria-current="location"]').get_attribute('data-target')=='chat-summary-one','同名小结一可准确定位')
        page.locator('a[data-target="chat-summary-two"]').click()
        page.wait_for_timeout(300)
        check(page.locator('[aria-current="location"]').get_attribute('data-target')=='chat-summary-two','同名小结二可准确定位')
        check(page.evaluate('document.querySelector("#chat-summary-two").closest("[data-part]").dataset.part')=='3','同名小结二位于第三片段')
        url_before=page.url
        page.locator('a[data-target="chat-next-answer-h1"]').click()
        page.wait_for_timeout(450)
        check(page.locator('[aria-current="location"]').get_attribute('data-target')=='chat-next-answer-h1','下一条回答的 H1 可定位')
        check(page.url==url_before,'目录点击不改变宿主 URL')
        page.locator('.docs-toc-panel').screenshot(path=str(output/'opendesk-toc-r3-chat-full.png'),animations='disabled')
        # Insert two headings with the same HTML ID, but different content owners.
        page.evaluate('''() => {for(const g of ['answer-1','answer-2']) {const h=document.createElement('h1');h.id='duplicate-h1';h.textContent=g+' 新章节';document.querySelector('[data-source-group="'+g+'"]').append(h)}}''')
        page.wait_for_timeout(250)
        labels=page.locator('a.docs-toc-link')
        check(labels.filter(has_text='answer-1 新章节').count()==1 and labels.filter(has_text='answer-2 新章节').count()==1,'重复 DOM id 的两个 H1 都不丢失')
        check(page.evaluate('document.querySelectorAll("#duplicate-h1").length')==2,'索引不会篡改原 DOM ID')
        second=labels.filter(has_text='answer-2 新章节')
        second.click()
        page.wait_for_timeout(400)
        check(page.locator('[aria-current="location"]').get_attribute('data-target')!='duplicate-h1','重复 ID 的后一条目录使用私有定位身份')
        check(page.evaluate('document.querySelectorAll("#duplicate-h1").length')==2,'定位后原 DOM 仍未改动')
        check(not errors,'JS 没有 pageerror: '+repr(errors))
        mobile=browser.new_page(viewport={'width':390,'height':844},reduced_motion='reduce')
        mobile.set_content(page_path.read_text(), wait_until="load")
        mobile.get_by_role('button',name='对话').click()
        mobile.get_by_role('button',name='完整目录').click()
        size=mobile.evaluate('''() => {let links=[...document.querySelectorAll('.docs-toc-link')];return {overflow:document.documentElement.scrollWidth>innerWidth,heights:links.map(el=>el.querySelector('.docs-toc-label').getBoundingClientRect().height),line:parseFloat(getComputedStyle(links[0]).lineHeight),footer:!!document.querySelector('.docs-toc-footer')}}''')
        check(not size['overflow'],'移动端无水平溢出')
        check(not size['footer'],'无底部上/下章翻页操作区')
        check(max(size['heights']) <= 2*size['line']+3,'所有目录行最多显示两行')
        mobile.locator('.docs-toc-panel').screenshot(path=str(output/'opendesk-toc-r3-chat-mobile.png'),animations='disabled')
        check(mobile.locator('a[data-target="chat-next-answer-h1"]').count()==1,'移动端可看见多个回答中的 H1')
        print('PASS',len(passed),'checks')
        for i,x in enumerate(passed,1):print(f'{i:02d} {x}')
    finally:
        browser.close()