

// 运营模块事件。
export const EVENT_OPERATE = {
	SCRIPT_RUN: 'SCRIPT_RUN',
	SCRIPT_STOP: 'SCRIPT_STOP',
	SCRIPT_RUN_BY_API: 'SCRIPT_RUN_BY_API',
	SCRIPT_STOP_BY_API: 'SCRIPT_STOP_BY_API',

	// 绑定设备 用户信息
	DEVICE_USER_INFO: 'OPERATE_DEVICE_USER_INFO',
	DEVICE_USER_INFO_UNBIND: 'OPERATE_DEVICE_USER_INFO_UNBIND', // 设备下线，取消绑定;
	DEVICE_INFO: 'OPERATE_DEVICE_INFO',   // 设备信息，主要是设备服务器端的id
}
